Python1810Axf/Python1810Axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf')),
]

Python1810Axf/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^home/$', views.home, name='home'),
    url(r'^market/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),
]

Python1810Axf/app/models.py
from django.db import models

# insert into axf_wheel(img,name,trackid) values("http://img01.bqstatic.com//upload/activity/2017031716035274.jpg@90Q.jpg","酸奶女王","21870"),("http://img01.bqstatic.com//upload/activity/2017031710450787.jpg@90Q.jpg","优选圣女果","21869"),("http://img01.bqstatic.com//upload/activity/2017030714522982.jpg@90Q.jpg","伊利酸奶大放价","21862"),("http://img01.bqstatic.com//upload/activity/2017032116081698.jpg@90Q.jpg","鲜货直供－窝夫小子","21770"),("http://img01.bqstatic.com//upload/activity/2017032117283348.jpg@90Q.jpg","鲜货直供－狼博森食品","21874");

# 基础类
class Base(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=8)

    class Meta:
        abstract = True


# 轮播图 模型类
class Wheel(Base):
    class Meta:
        db_table = 'axf_wheel'

Python1810Axf/app/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from app.models import Wheel


def home(request):

    # 获取轮播图数据
    wheels = Wheel.objects.all()


    data = {
        'wheels':wheels
    }

    return render(request, 'home/home.html', context=data)


def market(request):
    return render(request, 'market/market.html')


def cart(request):
    return render(request, 'cart/cart.html')


def mine(request):
    return render(request, 'mine/mine.html')

Python1810Axf/templates/base/base.html
{% extends  %}
{% load static %}

{% block extbasecss %}
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    {% block extcss %}
    {% endblock %}
{% endblock %}

{% block extbasejs %}
    <script src="{% static 'base/js/base.js' %}"></script>
    {% block extjs %}
    {% endblock %}
{% endblock %}

{% block body %}

    {#    头部#}
    {% block header %}
        <header>爱鲜蜂</header>
    {% endblock %}

    {#    主体内容#}
    <div class="hidescroll">
        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>

    {#    底部#}
    {% block footer %}
        <footer>
            <a href="{% url 'axf:home' %}" class="home">
                <dl>
                    <dt><span></span></dt>
                    <dd> 首页 </dd>
                </dl>
            </a>
            <a href="{% url 'axf:market' %}" class="market">
                <dl>
                    <dt><span></span></dt>
                    <dd> 闪购超市 </dd>
                </dl>
            </a>
            <a href="{% url 'axf:cart' %}" class="cart">
                <dl>
                    <dt><span></span></dt>
                    <dd> 购物车 </dd>
                </dl>
            </a>
            <a href="{% url 'axf:mine' %}" class="mine">
                <dl>
                    <dt><span></span></dt>
                    <dd> 我的 </dd>
                </dl>
            </a>
        </footer>
    {% endblock %}
{% endblock %}

Python1810Axf/templates/base/base_template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    {% block extbasecss %}
    {% endblock %}
</head>
<body>

{% block body %}

{% endblock %}


<script src="{% static 'base/js/jquery.min.js' %}"> </script>
<script src="{% static 'base/js/bootstrap.min.js' %}"></script>
<script src="{% static 'base/js/base_template.js' %}"></script>
{% block extbasejs %}
{% endblock %}

</body>
</html>

Python1810Axf/templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    购物车
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

{% block content %}
    购物车
{% endblock %}

Python1810Axf/templates/home/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    爱鲜蜂 | 首页
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'home/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/swiper.min.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'home/js/swiper.min.js' %}"></script>
    <script src="{% static 'home/js/home.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="home">

        <div class="swiper-container" id="top-swiper">
            <div class="swiper-wrapper">
{#                <div class="swiper-slide">Slide 1</div>#}
{#                <div class="swiper-slide">Slide 2</div>#}
{#                <div class="swiper-slide">Slide 3</div>#}
{#                <div class="swiper-slide">Slide 4</div>#}
{#                <div class="swiper-slide">Slide 5</div>#}
{#                <div class="swiper-slide">Slide 6</div>#}
{#                <div class="swiper-slide">Slide 7</div>#}
{#                <div class="swiper-slide">Slide 8</div>#}
{#                <div class="swiper-slide">Slide 9</div>#}
{#                <div class="swiper-slide">Slide 10</div>#}
                {% for wheel in wheels %}
                    <div class="swiper-slide">
                        <img src="{{ wheel.img }}" alt="">
                    </div>
                {% endfor %}
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination"></div>
            <!-- Add Arrows -->
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </div>
    </div>
{% endblock %}

Python1810Axf/templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    闪购超市
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}

{% block content %}
    闪购超市
{% endblock %}

Python1810Axf/templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    我的
{% endblock %}